// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ae_aux_rear_basic

#include "../ui.h"

void ui_accessoryStateScreen_screen_init(void)
{
ui_accessoryStateScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_accessoryStateScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_io1 = lv_switch_create(ui_accessoryStateScreen);
lv_obj_set_width( ui_io1, 230);
lv_obj_set_height( ui_io1, 59);
lv_obj_set_x( ui_io1, 213 );
lv_obj_set_y( ui_io1, 32 );
lv_obj_set_style_bg_color(ui_io1, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_io1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_io1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_io1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_io1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_io1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_io1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_io2 = lv_switch_create(ui_accessoryStateScreen);
lv_obj_set_width( ui_io2, 230);
lv_obj_set_height( ui_io2, 59);
lv_obj_set_x( ui_io2, 213 );
lv_obj_set_y( ui_io2, 1 );
lv_obj_set_align( ui_io2, LV_ALIGN_LEFT_MID );
lv_obj_set_style_bg_color(ui_io2, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_io2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_io2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_io2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_io2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_io2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_io2, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_io3 = lv_switch_create(ui_accessoryStateScreen);
lv_obj_set_width( ui_io3, 230);
lv_obj_set_height( ui_io3, 59);
lv_obj_set_x( ui_io3, 213 );
lv_obj_set_y( ui_io3, -30 );
lv_obj_set_align( ui_io3, LV_ALIGN_BOTTOM_LEFT );
lv_obj_set_style_bg_color(ui_io3, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_io3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_io3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_io3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_io3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_io3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_io3, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ioLabel1 = lv_label_create(ui_accessoryStateScreen);
lv_obj_set_width( ui_ioLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ioLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ioLabel1, -157 );
lv_obj_set_y( ui_ioLabel1, -101 );
lv_obj_set_align( ui_ioLabel1, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_ioLabel1,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_ioLabel1,"OP1");
lv_obj_clear_flag( ui_ioLabel1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_align(ui_ioLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ioLabel1, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ioLabel2 = lv_label_create(ui_accessoryStateScreen);
lv_obj_set_width( ui_ioLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ioLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ioLabel2, -157 );
lv_obj_set_y( ui_ioLabel2, 0 );
lv_obj_set_align( ui_ioLabel2, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_ioLabel2,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_ioLabel2,"OP2");
lv_obj_clear_flag( ui_ioLabel2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_align(ui_ioLabel2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ioLabel2, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ioLabel3 = lv_label_create(ui_accessoryStateScreen);
lv_obj_set_width( ui_ioLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ioLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ioLabel3, -157 );
lv_obj_set_y( ui_ioLabel3, 99 );
lv_obj_set_align( ui_ioLabel3, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_ioLabel3,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_ioLabel3,"OP3");
lv_obj_clear_flag( ui_ioLabel3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_align(ui_ioLabel3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ioLabel3, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_io1, ui_event_io1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_io2, ui_event_io2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_io3, ui_event_io3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_accessoryStateScreen, ui_event_accessoryStateScreen, LV_EVENT_ALL, NULL);

}
