// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: ae_aux

#include "../ui.h"

void ui_settingsStateScreen_screen_init(void)
{
ui_settingsStateScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_settingsStateScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_settingsLabel = lv_label_create(ui_settingsStateScreen);
lv_obj_set_width( ui_settingsLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_settingsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_settingsLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_settingsLabel,"Settings");
lv_obj_set_style_text_font(ui_settingsLabel, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_brightnessLabel = lv_label_create(ui_settingsStateScreen);
lv_obj_set_width( ui_brightnessLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_brightnessLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_brightnessLabel, 90 );
lv_obj_set_y( ui_brightnessLabel, 237 );
lv_obj_set_align( ui_brightnessLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_brightnessLabel,"Brightness");
lv_obj_set_style_text_font(ui_brightnessLabel, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_brightnessBar = lv_slider_create(ui_settingsStateScreen);
lv_slider_set_value( ui_brightnessBar, 100, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_brightnessBar)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_brightnessBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_brightnessBar, 183);
lv_obj_set_height( ui_brightnessBar, 15);
lv_obj_set_x( ui_brightnessBar, -129 );
lv_obj_set_y( ui_brightnessBar, 92 );
lv_obj_set_align( ui_brightnessBar, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_brightnessBar, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_brightnessBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_settingsStateScreen);
lv_obj_set_width( ui_Panel2, 191);
lv_obj_set_height( ui_Panel2, 37);
lv_obj_set_x( ui_Panel2, -131 );
lv_obj_set_y( ui_Panel2, -37 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Switch1 = lv_switch_create(ui_settingsStateScreen);
lv_obj_set_width( ui_Switch1, 50);
lv_obj_set_height( ui_Switch1, 25);
lv_obj_set_x( ui_Switch1, -193 );
lv_obj_set_y( ui_Switch1, -37 );
lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Switch1, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_Switch1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_brightnessLabel1 = lv_label_create(ui_settingsStateScreen);
lv_obj_set_width( ui_brightnessLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_brightnessLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_brightnessLabel1, -106 );
lv_obj_set_y( ui_brightnessLabel1, 112 );
lv_obj_set_align( ui_brightnessLabel1, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_brightnessLabel1,"LiFePO4");
lv_obj_set_style_text_font(ui_brightnessLabel1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_brightnessLabel2 = lv_label_create(ui_settingsStateScreen);
lv_obj_set_width( ui_brightnessLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_brightnessLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_brightnessLabel2, 90 );
lv_obj_set_y( ui_brightnessLabel2, 91 );
lv_obj_set_align( ui_brightnessLabel2, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_brightnessLabel2,"Battery \nChemistry");
lv_obj_set_style_text_font(ui_brightnessLabel2, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_brightnessBar, ui_event_brightnessBar, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_settingsStateScreen, ui_event_settingsStateScreen, LV_EVENT_ALL, NULL);

}
