// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_auxbatt;
lv_obj_t *ui_auxbattvoltagearc;
lv_obj_t *ui_auxbattpercentagelabel;
lv_obj_t *ui_battscreenlabel;
lv_obj_t *ui_batteries_legend_main;
lv_obj_t *ui_batteries_legend_aux;
lv_obj_t *ui_batteries_legend_aux_colour;
lv_obj_t *ui_batteries_legend_main_colour;
lv_obj_t *ui_mainbattpercentagelabel;
lv_obj_t *ui_mainbattvoltagearc;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_pirate_camp_co_[2] = {&ui_img_pirate_camp_co_275_png, &ui_img_pirate_camp_co_290_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui_auxbatt_screen_init(void)
{
ui_auxbatt = lv_obj_create(NULL);
lv_obj_clear_flag( ui_auxbatt, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_auxbattvoltagearc = lv_arc_create(ui_auxbatt);
lv_obj_set_width( ui_auxbattvoltagearc, 300);
lv_obj_set_height( ui_auxbattvoltagearc, 310);
lv_obj_set_align( ui_auxbattvoltagearc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_auxbattvoltagearc, 75);
lv_obj_set_style_arc_width(ui_auxbattvoltagearc, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_auxbattvoltagearc, 15, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_auxbattpercentagelabel = lv_label_create(ui_auxbatt);
lv_obj_set_width( ui_auxbattpercentagelabel, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_auxbattpercentagelabel, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_auxbattpercentagelabel, 0 );
lv_obj_set_y( ui_auxbattpercentagelabel, -30 );
lv_obj_set_align( ui_auxbattpercentagelabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_auxbattpercentagelabel,"75 %");
lv_obj_clear_flag( ui_auxbattpercentagelabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_auxbattpercentagelabel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_auxbattpercentagelabel, lv_color_hex(0x3B8CE8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_auxbattpercentagelabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_auxbattpercentagelabel, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_battscreenlabel = lv_label_create(ui_auxbatt);
lv_obj_set_width( ui_battscreenlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_battscreenlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_battscreenlabel, 0 );
lv_obj_set_y( ui_battscreenlabel, 130 );
lv_obj_set_align( ui_battscreenlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_battscreenlabel,"Batteries");
lv_obj_set_style_text_font(ui_battscreenlabel, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteries_legend_main = lv_label_create(ui_auxbatt);
lv_obj_set_width( ui_batteries_legend_main, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteries_legend_main, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batteries_legend_main, 195 );
lv_obj_set_y( ui_batteries_legend_main, -140 );
lv_obj_set_align( ui_batteries_legend_main, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteries_legend_main,"Main");
lv_obj_set_style_text_font(ui_batteries_legend_main, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteries_legend_aux = lv_label_create(ui_auxbatt);
lv_obj_set_width( ui_batteries_legend_aux, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteries_legend_aux, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batteries_legend_aux, -202 );
lv_obj_set_y( ui_batteries_legend_aux, -140 );
lv_obj_set_align( ui_batteries_legend_aux, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteries_legend_aux,"Aux");
lv_obj_set_style_text_font(ui_batteries_legend_aux, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteries_legend_aux_colour = lv_label_create(ui_auxbatt);
lv_obj_set_width( ui_batteries_legend_aux_colour, 15);
lv_obj_set_height( ui_batteries_legend_aux_colour, 15);
lv_obj_set_x( ui_batteries_legend_aux_colour, -155 );
lv_obj_set_y( ui_batteries_legend_aux_colour, -136 );
lv_obj_set_align( ui_batteries_legend_aux_colour, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteries_legend_aux_colour,"  ");
lv_obj_set_style_bg_color(ui_batteries_legend_aux_colour, lv_color_hex(0x4D89F0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batteries_legend_aux_colour, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteries_legend_main_colour = lv_label_create(ui_auxbatt);
lv_obj_set_width( ui_batteries_legend_main_colour, 15);
lv_obj_set_height( ui_batteries_legend_main_colour, 15);
lv_obj_set_x( ui_batteries_legend_main_colour, 139 );
lv_obj_set_y( ui_batteries_legend_main_colour, -136 );
lv_obj_set_align( ui_batteries_legend_main_colour, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteries_legend_main_colour,"  ");
lv_obj_set_style_bg_color(ui_batteries_legend_main_colour, lv_color_hex(0xBAC551), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batteries_legend_main_colour, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainbattpercentagelabel = lv_label_create(ui_auxbatt);
lv_obj_set_width( ui_mainbattpercentagelabel, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_mainbattpercentagelabel, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_mainbattpercentagelabel, 0 );
lv_obj_set_y( ui_mainbattpercentagelabel, 20 );
lv_obj_set_align( ui_mainbattpercentagelabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_mainbattpercentagelabel,"95 %");
lv_obj_clear_flag( ui_mainbattpercentagelabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_mainbattpercentagelabel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_mainbattpercentagelabel, lv_color_hex(0xCEE83B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainbattpercentagelabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mainbattpercentagelabel, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainbattvoltagearc = lv_arc_create(ui_auxbatt);
lv_obj_set_width( ui_mainbattvoltagearc, 240);
lv_obj_set_height( ui_mainbattvoltagearc, 240);
lv_obj_set_x( ui_mainbattvoltagearc, -1 );
lv_obj_set_y( ui_mainbattvoltagearc, -6 );
lv_obj_set_align( ui_mainbattvoltagearc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_mainbattvoltagearc, 95);
lv_obj_set_style_arc_width(ui_mainbattvoltagearc, 15, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_mainbattvoltagearc, lv_color_hex(0xBAC551), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_mainbattvoltagearc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_mainbattvoltagearc, 15, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_mainbattvoltagearc, lv_color_hex(0xBAC551), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mainbattvoltagearc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

}

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_auxbatt_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_auxbatt);
}
