// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: ae_aux

#ifndef _AE_AUX_UI_H
#define _AE_AUX_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_events.h"
void ui_event_splashScreen( lv_event_t * e);
extern lv_obj_t *ui_splashScreen;
void ui_event_batteryStateScreen( lv_event_t * e);
extern lv_obj_t *ui_batteryStateScreen;
extern lv_obj_t *ui_auxBattVoltageArc;
extern lv_obj_t *ui_auxBattPercentageLabel;
extern lv_obj_t *ui_warningLabel;
extern lv_obj_t *ui_mainBatteryStateLegend;
extern lv_obj_t *ui_auxBatteryStateLegend;
extern lv_obj_t *ui_auxBatteryStateLegendColour;
extern lv_obj_t *ui_mainBatteryStateLegendColour;
extern lv_obj_t *ui_auxCurrentBar;
extern lv_obj_t *ui_socLabel;
extern lv_obj_t *ui_auxBattAmpsLabel;
extern lv_obj_t *ui_auxState;
extern lv_obj_t *ui_auxBattVoltageLabel;
extern lv_obj_t *ui_mainBattVoltageLabel;
extern lv_obj_t *ui_auxRunFlatTime;
extern lv_obj_t *ui_socLabel1;
void ui_event_accessoryStateScreen( lv_event_t * e);
extern lv_obj_t *ui_accessoryStateScreen;
extern lv_obj_t *ui_io1;
extern lv_obj_t *ui_io2;
extern lv_obj_t *ui_io3;
void ui_event_io4( lv_event_t * e);
extern lv_obj_t *ui_io4;
extern lv_obj_t *ui_ioLabel1;
extern lv_obj_t *ui_ioLabel2;
extern lv_obj_t *ui_ioLabel3;
extern lv_obj_t *ui_ioLabel4;
void ui_event_settingsStateScreen( lv_event_t * e);
extern lv_obj_t *ui_settingsStateScreen;
extern lv_obj_t *ui_settingsLabel;
extern lv_obj_t *ui_brightnessLabel;
void ui_event_brightnessBar( lv_event_t * e);
extern lv_obj_t *ui_brightnessBar;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_Switch2;
extern lv_obj_t *ui_Switch3;
extern lv_obj_t *ui_Switch4;
extern lv_obj_t *ui_brightnessLabel1;
extern lv_obj_t *ui_brightnessLabel2;
extern lv_obj_t *ui_brightnessLabel3;
extern lv_obj_t *ui_brightnessLabel4;
extern lv_obj_t *ui_brightnessLabel5;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_ae_red_290_nobg_png);   // assets/ae_red_290_nobg.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
