// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_events.h"
extern lv_obj_t *ui_auxbatt;
extern lv_obj_t *ui_auxbattvoltagearc;
extern lv_obj_t *ui_auxbattpercentagelabel;
extern lv_obj_t *ui_battscreenlabel;
extern lv_obj_t *ui_batteries_legend_main;
extern lv_obj_t *ui_batteries_legend_aux;
extern lv_obj_t *ui_batteries_legend_aux_colour;
extern lv_obj_t *ui_batteries_legend_main_colour;
extern lv_obj_t *ui_mainbattpercentagelabel;
extern lv_obj_t *ui_mainbattvoltagearc;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_pirate_camp_co_275_png);   // assets/pirate_camp_co_275.png
LV_IMG_DECLARE( ui_img_pirate_camp_co_290_png);   // assets/pirate_camp_co_290.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
