// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: ae_aux_front

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void hp1ToggleFunction(lv_event_t * e);
void hp2ToggleFunction(lv_event_t * e);
void lp1ToggleFunction(lv_event_t * e);
void lp2ToggleFunction(lv_event_t * e);
void hp1ToggleFunction(lv_event_t * e);
void hp2ToggleFunction(lv_event_t * e);
void lp1ToggleFunction(lv_event_t * e);
void lp2ToggleFunction(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
